export interface EmojiItem {
  char: string;
  keywords: string[];
  category: string;
}

export const EMOJI_CATEGORIES = [
  "All",
  "Tools",
  "Construction",
  "Office",
  "Tech",
  "Business",
  "Medical",
  "Food",
  "Transport",
  "Household",
  "Nature",
  "Symbols"
];

export const EMOJI_LIST: EmojiItem[] = [
  // Tools
  { char: "🔧", keywords: ["wrench", "fix", "repair", "tool"], category: "Tools" },
  { char: "🔨", keywords: ["hammer", "nail", "build", "construction"], category: "Tools" },
  { char: "🛠️", keywords: ["hammer", "wrench", "tools", "fix"], category: "Tools" },
  { char: "🪛", keywords: ["screwdriver", "tool", "fix"], category: "Tools" },
  { char: "🔩", keywords: ["nut", "bolt", "screw", "metal"], category: "Tools" },
  { char: "⚙️", keywords: ["gear", "settings", "cog", "engine"], category: "Tools" },
  { char: "🗜️", keywords: ["clamp", "vise", "tool"], category: "Tools" },
  { char: "⛏️", keywords: ["pick", "mining", "tool"], category: "Tools" },
  { char: "🪓", keywords: ["axe", "wood", "chop"], category: "Tools" },
  { char: "🪚", keywords: ["saw", "wood", "cut"], category: "Tools" },
  { char: "🪜", keywords: ["ladder", "climb", "height"], category: "Tools" },
  { char: "⛓️", keywords: ["chains", "metal", "lock"], category: "Tools" },
  { char: "🧲", keywords: ["magnet", "magnetic", "attract"], category: "Tools" },
  { char: "🧰", keywords: ["toolbox", "kit", "storage"], category: "Tools" },
  { char: "🔦", keywords: ["flashlight", "light", "torch"], category: "Tools" },
  
  // Construction
  { char: "🏗️", keywords: ["building", "construction", "crane"], category: "Construction" },
  { char: "🧱", keywords: ["brick", "wall", "build"], category: "Construction" },
  { char: "🪵", keywords: ["wood", "log", "lumber"], category: "Construction" },
  { char: "🚧", keywords: ["barrier", "construction", "warning"], category: "Construction" },
  { char: "🛑", keywords: ["stop", "sign", "warning"], category: "Construction" },
  { char: "⚓", keywords: ["anchor", "ship", "marine"], category: "Construction" },
  { char: "🦺", keywords: ["vest", "safety", "clothing"], category: "Construction" },
  { char: "⛑️", keywords: ["helmet", "safety", "hat"], category: "Construction" },
  { char: "🏠", keywords: ["house", "home", "building"], category: "Construction" },
  { char: "🏡", keywords: ["house", "garden", "home"], category: "Construction" },
  { char: "🏢", keywords: ["office", "building", "work"], category: "Construction" },
  { char: "🏭", keywords: ["factory", "industry", "plant"], category: "Construction" },
  
  // Office & Business
  { char: "💼", keywords: ["briefcase", "work", "business"], category: "Business" },
  { char: "📁", keywords: ["folder", "file", "document"], category: "Business" },
  { char: "📂", keywords: ["open", "folder", "file"], category: "Business" },
  { char: "📅", keywords: ["calendar", "date", "schedule"], category: "Office" },
  { char: "📝", keywords: ["memo", "note", "write"], category: "Office" },
  { char: "🖊️", keywords: ["pen", "write", "ink"], category: "Office" },
  { char: "✂️", keywords: ["scissors", "cut", "tool"], category: "Office" },
  { char: "📎", keywords: ["paperclip", "hold", "office"], category: "Office" },
  { char: "📌", keywords: ["pushpin", "tack", "board"], category: "Office" },
  { char: "📍", keywords: ["pin", "location", "map"], category: "Office" },
  { char: "📏", keywords: ["ruler", "measure", "length"], category: "Office" },
  { char: "📐", keywords: ["triangle", "measure", "math"], category: "Office" },
  { char: "🗑️", keywords: ["trash", "bin", "garbage"], category: "Office" },
  { char: "📊", keywords: ["chart", "bar", "graph"], category: "Business" },
  { char: "📈", keywords: ["chart", "up", "growth"], category: "Business" },
  { char: "📉", keywords: ["chart", "down", "loss"], category: "Business" },
  { char: "💹", keywords: ["chart", "jen", "market"], category: "Business" },
  { char: "💰", keywords: ["money", "bag", "cash"], category: "Business" },
  { char: "💸", keywords: ["money", "flying", "cash"], category: "Business" },
  { char: "💳", keywords: ["credit", "card", "pay"], category: "Business" },
  { char: "🧾", keywords: ["receipt", "bill", "paper"], category: "Business" },
  { char: "⚖️", keywords: ["scale", "balance", "law"], category: "Business" },
  { char: "🏦", keywords: ["bank", "building", "finance"], category: "Business" },
  
  // Tech
  { char: "💻", keywords: ["laptop", "computer", "tech"], category: "Tech" },
  { char: "🖥️", keywords: ["desktop", "computer", "screen"], category: "Tech" },
  { char: "🖨️", keywords: ["printer", "paper", "copy"], category: "Tech" },
  { char: "🖱️", keywords: ["mouse", "click", "computer"], category: "Tech" },
  { char: "📱", keywords: ["phone", "mobile", "cell"], category: "Tech" },
  { char: "📷", keywords: ["camera", "photo", "picture"], category: "Tech" },
  { char: "📹", keywords: ["video", "camera", "film"], category: "Tech" },
  { char: "📞", keywords: ["phone", "call", "telephone"], category: "Tech" },
  { char: "📠", keywords: ["fax", "machine", "print"], category: "Tech" },
  { char: "💡", keywords: ["idea", "light", "bulb"], category: "Tech" },
  { char: "🔋", keywords: ["battery", "power", "energy"], category: "Tech" },
  { char: "🔌", keywords: ["plug", "power", "cord"], category: "Tech" },
  { char: "📡", keywords: ["satellite", "dish", "signal"], category: "Tech" },
  { char: "🎙️", keywords: ["microphone", "audio", "sound"], category: "Tech" },
  
  // Household & Services
  { char: "🧹", keywords: ["broom", "sweep", "clean"], category: "Household" },
  { char: "🧽", keywords: ["sponge", "clean", "wash"], category: "Household" },
  { char: "🧼", keywords: ["soap", "wash", "clean"], category: "Household" },
  { char: "🚿", keywords: ["shower", "wash", "water"], category: "Household" },
  { char: "🛁", keywords: ["tub", "bath", "wash"], category: "Household" },
  { char: "🚽", keywords: ["toilet", "bathroom", "restroom"], category: "Household" },
  { char: "🛋️", keywords: ["couch", "sofa", "furniture"], category: "Household" },
  { char: "🪑", keywords: ["chair", "seat", "furniture"], category: "Household" },
  { char: "🛏️", keywords: ["bed", "sleep", "furniture"], category: "Household" },
  { char: "🚪", keywords: ["door", "entry", "exit"], category: "Household" },
  { char: "🔑", keywords: ["key", "lock", "open"], category: "Household" },
  { char: "🔐", keywords: ["lock", "key", "secure"], category: "Household" },
  { char: "🧺", keywords: ["basket", "laundry", "wash"], category: "Household" },
  { char: "🧯", keywords: ["extinguisher", "fire", "safety"], category: "Household" },
  { char: "🧊", keywords: ["ice", "cube", "cold"], category: "Household" },
  
  // Medical
  { char: "🏥", keywords: ["hospital", "clinic", "medical"], category: "Medical" },
  { char: "🚑", keywords: ["ambulance", "emergency", "medical"], category: "Medical" },
  { char: "💊", keywords: ["pill", "drug", "medicine"], category: "Medical" },
  { char: "💉", keywords: ["syringe", "shot", "needle"], category: "Medical" },
  { char: "🩸", keywords: ["blood", "drop", "donor"], category: "Medical" },
  { char: "🌡️", keywords: ["temperature", "thermometer", "hot"], category: "Medical" },
  { char: "🩹", keywords: ["bandage", "aid", "hurt"], category: "Medical" },
  { char: "🩺", keywords: ["stethoscope", "doctor", "heart"], category: "Medical" },
  { char: "🧬", keywords: ["dna", "gene", "science"], category: "Medical" },
  { char: "🔬", keywords: ["microscope", "science", "lab"], category: "Medical" },
  { char: "🦷", keywords: ["tooth", "dentist", "medical"], category: "Medical" },
  { char: "👓", keywords: ["glasses", "vision", "eye"], category: "Medical" },
  
  // Transport
  { char: "🚗", keywords: ["car", "auto", "vehicle"], category: "Transport" },
  { char: "🚕", keywords: ["taxi", "cab", "vehicle"], category: "Transport" },
  { char: "🚌", keywords: ["bus", "school", "vehicle"], category: "Transport" },
  { char: "🏎️", keywords: ["car", "race", "sport"], category: "Transport" },
  { char: "🚓", keywords: ["police", "car", "cop"], category: "Transport" },
  { char: "🚒", keywords: ["fire", "truck", "emergency"], category: "Transport" },
  { char: "🚚", keywords: ["truck", "delivery", "haul"], category: "Transport" },
  { char: "🚛", keywords: ["truck", "semi", "haul"], category: "Transport" },
  { char: "🚜", keywords: ["tractor", "farm", "vehicle"], category: "Transport" },
  { char: "🏍️", keywords: ["motorcycle", "bike", "vehicle"], category: "Transport" },
  { char: "✈️", keywords: ["plane", "fly", "travel"], category: "Transport" },
  { char: "🚁", keywords: ["helicopter", "fly", "air"], category: "Transport" },
  { char: "🚢", keywords: ["ship", "boat", "sea"], category: "Transport" },
  { char: "🚀", keywords: ["rocket", "fly", "space"], category: "Transport" },
  { char: "🚦", keywords: ["traffic", "light", "signal"], category: "Transport" },
  { char: "⛽", keywords: ["gas", "fuel", "station"], category: "Transport" },
  
  // Food
  { char: "🍔", keywords: ["burger", "food", "eat"], category: "Food" },
  { char: "🍕", keywords: ["pizza", "food", "slice"], category: "Food" },
  { char: "🌮", keywords: ["taco", "food", "mexican"], category: "Food" },
  { char: "🥗", keywords: ["salad", "healthy", "food"], category: "Food" },
  { char: "🥪", keywords: ["sandwich", "lunch", "food"], category: "Food" },
  { char: "🍳", keywords: ["egg", "breakfast", "cook"], category: "Food" },
  { char: "🥘", keywords: ["pan", "food", "cook"], category: "Food" },
  { char: "🍦", keywords: ["ice", "cream", "dessert"], category: "Food" },
  { char: "🍪", keywords: ["cookie", "sweet", "dessert"], category: "Food" },
  { char: "☕", keywords: ["coffee", "drink", "cup"], category: "Food" },
  { char: "🍷", keywords: ["wine", "drink", "alcohol"], category: "Food" },
  { char: "🍺", keywords: ["beer", "drink", "alcohol"], category: "Food" },
  { char: "🍽️", keywords: ["plate", "fork", "knife"], category: "Food" },
  { char: "🥐", keywords: ["croissant", "bread", "bakery"], category: "Food" },
  { char: "🥖", keywords: ["bread", "bakery", "food"], category: "Food" },
  
  // Nature
  { char: "🌳", keywords: ["tree", "nature", "forest"], category: "Nature" },
  { char: "🌲", keywords: ["pine", "tree", "nature"], category: "Nature" },
  { char: "🌴", keywords: ["palm", "tree", "nature"], category: "Nature" },
  { char: "🌵", keywords: ["cactus", "plant", "desert"], category: "Nature" },
  { char: "🌾", keywords: ["glass", "plant", "farm"], category: "Nature" },
  { char: "🌿", keywords: ["herb", "plant", "nature"], category: "Nature" },
  { char: "🌻", keywords: ["sunflower", "flower", "nature"], category: "Nature" },
  { char: "🌺", keywords: ["flower", "nature", "plant"], category: "Nature" },
  { char: "🔥", keywords: ["fire", "burn", "hot"], category: "Nature" },
  { char: "💧", keywords: ["water", "drop", "wet"], category: "Nature" },
  { char: "⚡", keywords: ["bolt", "electric", "power"], category: "Nature" },
  { char: "❄️", keywords: ["snow", "cold", "weather"], category: "Nature" },
  { char: "☀️", keywords: ["sun", "day", "light"], category: "Nature" },
  { char: "♻️", keywords: ["recycle", "green", "cycle"], category: "Nature" },
  
  // Symbols
  { char: "⭐", keywords: ["star", "rating", "favorite"], category: "Symbols" },
  { char: "🌟", keywords: ["star", "glow", "shine"], category: "Symbols" },
  { char: "✨", keywords: ["sparkle", "shine", "clean"], category: "Symbols" },
  { char: "💯", keywords: ["100", "score", "perfect"], category: "Symbols" },
  { char: "✅", keywords: ["check", "yes", "correct"], category: "Symbols" },
  { char: "❌", keywords: ["cross", "no", "wrong"], category: "Symbols" },
  { char: "❗", keywords: ["exclamation", "attention", "mark"], category: "Symbols" },
  { char: "❓", keywords: ["question", "help", "mark"], category: "Symbols" },
  { char: "🏁", keywords: ["flag", "finish", "race"], category: "Symbols" },
  { char: "🏆", keywords: ["trophy", "win", "award"], category: "Symbols" },
  { char: "🥇", keywords: ["medal", "first", "win"], category: "Symbols" },
  { char: "🎯", keywords: ["target", "bullseye", "goal"], category: "Symbols" },
  { char: "📢", keywords: ["speaker", "announce", "sound"], category: "Symbols" },
  { char: "🔔", keywords: ["bell", "alert", "ring"], category: "Symbols" },
  { char: "💎", keywords: ["diamond", "gem", "jewel"], category: "Symbols" },
  { char: "🧡", keywords: ["heart", "love", "orange"], category: "Symbols" },
  { char: "💙", keywords: ["heart", "love", "blue"], category: "Symbols" },
  { char: "💚", keywords: ["heart", "love", "green"], category: "Symbols" },
  { char: "🖤", keywords: ["heart", "love", "black"], category: "Symbols" },
];
